<?php

declare(strict_types=1);

namespace App\Module\Catalog\Tests\Integration;

use App\Infrastructure\Symfony\Kernel;
use App\Module\Catalog\Domain\Event\ProductCreatedEvent;
use App\Module\Catalog\Domain\Event\ProductNameChangedEvent;
use App\Module\Catalog\Domain\Event\ProductPriceChangedEvent;
use App\Module\Catalog\Domain\Event\ProductRemovedEvent;
use App\Module\Catalog\Domain\ProductId;
use App\Module\Catalog\Domain\ProductName;
use App\Module\Catalog\Domain\ProductPrice;
use App\Module\Catalog\Infrastructure\Doctrine\Entity\ProductReadModel;
use App\Module\Catalog\Infrastructure\Doctrine\Projection\ProductProjection;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

final class ProductProjectionTest extends KernelTestCase
{
    const CURRENCY = 'PLN';
    const PRICE = '20';
    const NAME = 'test';
    private ProductProjection $projection;
    private EntityRepository $repo;
    private EntityManager $em;

    protected static $class = Kernel::class;

    protected function setUp()
    {
        parent::setUp();
        self::bootKernel();

        $this->projection = self::$container->get(ProductProjection::class);
        $this->repo = self::$container->get('doctrine.orm.entity_manager')
            ->getRepository(ProductReadModel::class);
        $this->em = self::$container->get('doctrine.orm.entity_manager');
        $this->em->beginTransaction();
    }

    public function testWhenProductCreatedEvent(): void
    {
        $id = ProductId::generate();
        $event = new ProductCreatedEvent(
            $id,
            ProductName::fromString(self::NAME),
            ProductPrice::fromString(self::PRICE, self::CURRENCY)
        );

        $this->projection->whenProductCreatedEvent($event);

        /** @var ProductReadModel $product */
        $product = $this->repo->find($id->getId());
        self::assertInstanceOf(ProductReadModel::class, $product);
        self::assertTrue($product->getId()->equals($id->getId()));
        self::assertSame(self::NAME, $product->getName());
        self::assertSame(self::PRICE, $product->getPrice());
        self::assertSame(self::CURRENCY, $product->getCurrency());
    }

    public function testWhenProductNameChangedEvent(): void
    {
        $id = $this->createProduct();
        $event = new ProductNameChangedEvent(
            $id,
            ProductName::fromString('test2')
        );

        $this->projection->whenProductNameChangedEvent($event);
        $product = $this->repo->find($id->getId());
        self::assertInstanceOf(ProductReadModel::class, $product);
        self::assertSame('test2', $product->getName());
    }

    public function testWhenProductPriceChangedEvent(): void
    {
        $id = $this->createProduct();
        $event = new ProductPriceChangedEvent(
            $id,
            ProductPrice::fromString('30', self::CURRENCY)
        );

        $this->projection->whenProductPriceChangedEvent($event);
        $product = $this->repo->find($id->getId());
        self::assertInstanceOf(ProductReadModel::class, $product);
        self::assertSame('30', $product->getPrice());
        self::assertSame(self::CURRENCY, $product->getCurrency());
    }

    public function testWhenProductRemovedEvent(): void
    {
        $id = $this->createProduct();
        $event = new ProductRemovedEvent(
            $id
        );

        $this->projection->whenProductRemovedEvent($event);
        $product = $this->repo->find($id->getId());
        self::assertNull($product);
    }

    protected function tearDown(): void
    {
        $this->em->rollback();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    private function createProduct(): ProductId
    {
        $id = ProductId::generate();
        $product = (new ProductReadModel())
            ->setId($id->getId())
            ->setName(self::NAME)
            ->setPrice(self::PRICE)
            ->setCurrency(self::CURRENCY);
        $this->em->persist($product);
        $this->em->flush();

        return $id;
    }
}
