version: '3.1'

services:

    php:
        build:
            context: ./
            dockerfile: ./Dockerfile
        volumes:
            - ./:/var/www/html:delegated
        env_file:
            - .env
        ports:
            - "9999:80"
        links:
            - postgres

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=cart-api
            - POSTGRES_USER=cart-api
            - POSTGRES_DB=cart-api
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 9998:5432
#
#    rabbit:
#        image: "rabbitmq:3.8-rc-management-alpine"
#        environment:
#            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
#            RABBITMQ_DEFAULT_USER: "rabbitmq"
#            RABBITMQ_DEFAULT_PASS: "rabbitmq"
#            RABBITMQ_DEFAULT_VHOST: "/"
#        ports:
#            - "9997:15672"
#            - "9996:5672"

volumes:
    db_data: