# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.infrastructure.symfony.dupa_command:
        class: App\Infrastructure\Symfony\DupaCommand
        tags:
            - { name: console.command }

    App\Module\Cart\Domain\CartRepositoryInterface: '@App\Module\Cart\Infrastructure\Repository\CartRepository'

    App\Module\Catalog\Domain\ProductRepositoryInterface: '@App\Module\Catalog\Infrastructure\Repository\ProductRepository'

    App\Module\Cart\Infrastructure\Doctrine\Projection\CartProjection:
        public: true
    App\Module\Catalog\Infrastructure\Doctrine\Projection\ProductProjection:
        public: true

    App\Infrastructure\Symfony\RequestDTOResolver:
        tags:
            - { name: controller.request_value_resolver, priority: 50 }

    App\Infrastructure\Symfony\JsonBodyParserSubscriber:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 100 }

    App\Infrastructure\CommandBus\CommandBus:
        calls:
            - method: addHandler
              arguments:
                - '@App\Module\Cart\Application\CreateCart\CreateCartHandler'
            - method: addHandler
              arguments:
                - '@App\Module\Cart\Application\AddProductToCart\AddProductToCartHandler'
            - method: addHandler
              arguments:
                - '@App\Module\Cart\Application\RemoveProductFromCart\RemoveProductFromCartHandler'
            - method: addHandler
              arguments:
                - '@App\Module\Catalog\Application\CreateProduct\CreateProductHandler'
            - method: addHandler
              arguments:
                - '@App\Module\Catalog\Application\ChangeProductName\ChangeProductNameHandler'
            - method: addHandler
              arguments:
                - '@App\Module\Catalog\Application\ChangeProductPrice\ChangeProductPriceHandler'
            - method: addHandler
              arguments:
                - '@App\Module\Catalog\Application\RemoveProduct\RemoveProductHandler'

    App\Infrastructure\Symfony\ExceptionSubscriber:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }