apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "php" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
    "helm.sh/hook-weight": "-5"
data:
  APP_ENV: {{ .Values.php.env | quote }}
  APP_DEBUG: {{ .Values.php.debug | quote }}
  APP_SECRET: {{ .Values.php.secret | quote }}
  DATABASE_URL: {{ .Values.php.database | quote }}
  RABBITMQ_HOST: {{ .Values.php.rabbit_host | quote }}
  RABBITMQ_USER: {{ .Values.php.rabbit_user | quote }}
  RABBITMQ_PASSWORD: {{ .Values.php.rabbit_password | quote }}
  RABBITMQ_PORT: {{ .Values.php.rabbit_port | quote }}